USE punarvastra;

INSERT INTO users (full_name, username, email, password, phone, address, role, approved) VALUES
                                                                                             ('System Admin', 'admin', 'admin@punarvastra.np', '$2a$10$0dD2XgNDyjF2cMdl82XdWuBlXBfe5Xdh2Be/Eds/8olaMUkmIy8O6', '9800000001', 'Kathmandu', 'ADMIN', TRUE),
                                                                                             ('Test User', 'testuser', 'testuser@punarvastra.np', '$2a$10$08/2n3/PaQEEnL0vIozSO.Vl18NGgpfnfO.zyhKpjr4nACq9iiSj.', '9812345678', 'Lalitpur, Ward 5', 'USER', TRUE),
                                                                                             ('Pending Demo', 'pendinguser', 'pending@punarvastra.np', '$2a$10$eJinWzBGq1CSgyVr6aSkr.3UlI7Qtie6BNQ0G8dvW9H2meFA6lQk.', '9823456789', 'Bhaktapur', 'USER', FALSE);

INSERT INTO categories (name, slug, description) VALUES
                                                     ('Men', 'men', 'Second-hand menswear from Kathmandu valley'),
                                                     ('Women', 'women', 'Dresses, tops, and traditional wear'),
                                                     ('Kids', 'kids', 'Gently used clothing for children'),
                                                     ('Accessories', 'accessories', 'Bags, scarves, belts, and more');

INSERT INTO products (seller_id, title, description, price, size, product_condition, brand, image, stock, category_id, listing_status) VALUES
                                                                                                                                           (NULL, 'Wool Shawl — Dhaka Weave', 'Hand-loomed accent piece, light wear. Perfect for winter evenings in Pokhara.', 1200.00, 'Free', 'Like New', 'Local Artisan', 'placeholder.png', 2, 4, 'APPROVED'),
                                                                                                                                           (NULL, 'Men''s Cotton Kurta — White', 'Classic white kurta, festival ready. Dry-cleaned.', 850.00, 'L', 'Good', 'Generic', 'placeholder.png', 3, 1, 'APPROVED'),
                                                                                                                                           (NULL, 'Women''s Linen Blouse', 'Breathable linen, earth tone. Office or casual.', 650.00, 'M', 'Like New', 'Zara', 'placeholder.png', 2, 2, 'APPROVED'),
                                                                                                                                           (NULL, 'Kids Puffer Jacket', 'Warm jacket for trekking season, minor scuff on cuff.', 450.00, 'S', 'Good', 'Uniqlo', 'placeholder.png', 1, 3, 'APPROVED'),
                                                                                                                                           (NULL, 'Leather Crossbody Bag', 'Genuine leather, brass hardware. Patina adds character.', 1800.00, 'Free', 'Good', 'Local Leather', 'placeholder.png', 1, 4, 'APPROVED'),
                                                                                                                                           (NULL, 'Men''s Denim Jeans — Slim', 'Indigo denim, hem intact.', 700.00, '32', 'Good', 'Levi''s', 'placeholder.png', 4, 1, 'APPROVED'),
                                                                                                                                           (NULL, 'Printed Summer Dress', 'Floral midi dress, ideal for Terai heat.', 920.00, 'S', 'Like New', 'H&M', 'placeholder.png', 2, 2, 'APPROVED'),
                                                                                                                                           (NULL, 'Wool Beanie — Maroon', 'Thick knit, no pulls.', 280.00, 'Free', 'New', 'Handmade', 'placeholder.png', 5, 4, 'APPROVED'),
                                                                                                                                           (2, 'Vintage Band T-shirt', 'Concert tee from 2010s, soft fade.', 400.00, 'M', 'Fair', 'Vintage', 'placeholder.png', 1, 1, 'APPROVED'),
                                                                                                                                           (2, 'Silk Scarf — Peacock Motif', 'Gift-quality scarf, stored in box.', 550.00, 'Free', 'Like New', 'Nepal Silk', 'placeholder.png', 2, 4, 'APPROVED'),
                                                                                                                                           (NULL, 'Trail Running Shoes', 'Grip still strong; cleaned after last run.', 1500.00, '42', 'Good', 'Salomon', 'placeholder.png', 1, 1, 'APPROVED'),
                                                                                                                                           (NULL, 'Handwoven Dhaka Topi', 'Traditional cap, wedding season staple.', 350.00, 'Free', 'New', 'Bhaktapur Weavers', 'placeholder.png', 6, 4, 'APPROVED'),
                                                                                                                                           (NULL, 'Corduroy Trousers — Olive', 'High rise, ankle crop.', 680.00, 'M', 'Good', 'COS', 'placeholder.png', 2, 2, 'APPROVED'),
                                                                                                                                           (NULL, 'School Uniform Shirt — White', 'Stain-free, outgrown.', 220.00, '12', 'Good', 'School Brand', 'placeholder.png', 3, 3, 'APPROVED'),
                                                                                                                                           (NULL, 'Merino Base Layer', 'Layering piece for Annapurna circuit.', 890.00, 'L', 'Like New', 'Icebreaker', 'placeholder.png', 2, 1, 'APPROVED'),
                                                                                                                                           (NULL, 'Embroidered Waistcoat', 'Wedding waistcoat, gold thread detail.', 2100.00, 'L', 'Like New', 'Bespoke', 'placeholder.png', 1, 1, 'APPROVED'),
                                                                                                                                           (NULL, 'Canvas Tote — Bookstore Print', 'Sturdy tote from Patan book fair.', 300.00, 'Free', 'Good', 'Event', 'placeholder.png', 4, 4, 'APPROVED'),
                                                                                                                                           (NULL, 'Fleece Zip Hoodie', 'Cozy grey hoodie, university logo faded.', 520.00, 'XL', 'Fair', 'Champion', 'placeholder.png', 2, 1, 'APPROVED'),
                                                                                                                                           (NULL, 'Ankara Print Skirt', 'Vibrant wax print, elastic waist.', 750.00, 'M', 'Good', 'Market Find', 'placeholder.png', 1, 2, 'APPROVED'),
                                                                                                                                           (NULL, 'Baby Romper Set (2 pcs)', 'Organic cotton, gentle wash only.', 380.00, '6-12m', 'Like New', 'Carter''s', 'placeholder.png', 2, 3, 'APPROVED'),
                                                                                                                                           (2, 'Designer Sunglasses', 'UV400, micro scratches on left lens.', 950.00, 'Free', 'Good', 'Ray-Ban style', 'placeholder.png', 1, 4, 'PENDING'),
                                                                                                                                           (2, 'Rejected Sample Hoodie', 'Listing rejected for demo — seller may resubmit.', 400.00, 'M', 'Good', 'Unknown', 'placeholder.png', 1, 1, 'REJECTED');

INSERT INTO inquiries (name, email, subject, message, is_read) VALUES
    ('Ramesh K.', 'ramesh@example.com', 'Bulk donation', 'We have 20kg of clothes to donate from our office.', FALSE);
